#!/bin/bash

basen() {
  local -a colros
  colors=( $( 'ls' "${MDX_REPOS_ROOT}/base16-shell"/base16-*.sh ) )

  if [ -n "${colors[*]}" ]; then
    local i=$(( RANDOM % ${#colors[@]} ))
    local colorscheme=${colors[i]}
    source ${colorscheme}
    echo "\e[33m[base16 colorscheme]: \e[5;34m$(basename ${colorscheme} .sh)\e[0m"
  fi
}

# vim: filetype=zsh
