#!/bin/bash

if [ ! -d "${MDX_REPOS_ROOT}/base16-shell" ]; then
  printf "\e[33mneed [base16-shell], installing ...\e[0m\n"
  git clone "https://github.com/chriskempson/base16-shell.git" \
    "${MDX_REPOS_ROOT}/base16-shell"
fi

basen() {
  local -a colros
  colors=( $( 'ls' "${MDX_REPOS_ROOT}/base16-shell"/base16-*.dark.sh ) )

  if [ "${#colors[*]}" -gt 0 ]; then
    local i=$(( RANDOM % ${#colors[@]} ))
    local colorscheme=${colors[i]}
    source ${colorscheme}

    export MDX_BASE_COLOR="$(basename ${colorscheme} .sh)"
    printf "\e[33m[shell colorscheme]: \e[1;35m${MDX_BASE_COLOR}\e[0m\n"
  fi
}

# vim: filetype=zsh
