#!/usr/bin/env bash
#x cmdhub: Delete conflicting files in my cloud repository

cloud_path_on_pc="/Volumes/Apple_Store/Cloud"
cloud_path_on_mbp="/Users/mudox/Dropbox"

if [[ -e "${cloud_path_on_mbp}" ]]; then
  dest_path="${cloud_path_on_mbp}"
else
  dest_path="${cloud_path_on_pc}"
fi

gfind "${dest_path}" -iname '*NSConflict*' -print -delete
gfind "${dest_path}" -iname '*conflicted copy*' -print -delete
gfind "${dest_path}" -iname '*-冲突-*' -print -delete

# vim: ft=sh
