#!/usr/bin/env bash
#x cmdhub: Create a new git repo and corresponding Github repo
set -euo pipefail

source ~/Git/dot-files/bash/lib/jack

usage='$0 [repo-name]'

if [[ $# -eq 0 ]]; then
  read -p 'Name repo name: ' repo_name
elif [[ $# -eq 1 ]]; then
  repo_name="$1"
else
  jackError "$usage"
  exit 1
fi

jackInfo '\nInitializing Git repo'
sleep 1

git init
git add --all
git commit -m 'Initial commit'

jackInfo "\nCreating Github repo: github.com/mudox/${repo_name}"
sleep 1

hub create "${repo_name}"

jackInfo '\nMaking .gitignore'
sleep 1

types=$(git ignore list | tr ',' '\n' | fzf -m)
for type in ${types}; do
  echo "- ${type}"
  git ignore "${type}" >> .gitignore
done

jackInfo '\nPerforming initial push'
sleep 1

git push --set-upstream origin master

jackInfo "\nDone, bringing you to github.com/mudox/${repo_name}"
sleep 1

hub browse
