#!/usr/bin/env bash
#x cmdhub: Start commonly used tmux sessions
set -euo pipefail

# get tty size
set +u
  if [[ -n "$TMUX" ]]; then
    tty_width="$(tmux list-clients -F '#{client_width}') | head -n1"
    tty_height="$(tmux list-clients -F '#{client_height}') | head -n1"
  else
    tty_width=$(tput lines)
    tty_height=$(tput cols)
  fi
set -u

source ~/Git/dot-files/bash/lib/jack

# common sessions
for s in Configure Dashboard Play Xcode; do
  session_file="$HOME/Git/dot-files/tmux/sessions/$s"
  if [[ -f $session_file ]]; then
    jackInfo "\nStarting $s\n"
    bash "$session_file"                \
      && jackVerbose "\nwarming for 1s" \
      && sleep 1
  else
    jackError "Missing session file: $session_file\n"
  fi
done

# the special Tav session
jackInfo "\nStarting Tmux\n"
tav="${HOME}/Develop/Python/tav/tav.py"
"${tav}" snapshot
tmux new-session     \
  -s Tmux            \
  -n Navigator       \
  -x "${tty_width}"  \
  -y "${tty_height}" \
  -d                 \
  "${tav}" serve

tmux attach-session -t '@0'
