#!/usr/bin/env bash
#x cmdhub: Start commonly used tmux sessions

source ~/Git/dot-files/bash/lib/jack

for s in Configure Dashboard Play Xcode; do
  session_file="$HOME/Git/dot-files/tmux/sessions/$s.tmux-session.sh"
  if [[ -f $session_file ]]; then
    jackInfo "\nStarting $s\n"
    bash "$session_file"                \
      && jackVerbose "\nwarming for 1s" \
      && sleep 1
  else
    jackError "Missing session file: $session_file\n"
  fi
done

tmux attach-session -t '@0'
