#!/usr/bin/env bash
#x cmdhub: Start commonly used tmux sessions

# $1: session id of interest
is_session_exists() {
  tmux list-session -F '#{session_name}' 2>&1 | grep -q "^$1$"
}

# $1: the yml name to let tmuxinator to start
start_session() {
  if tmux has-session -t $1 &>/dev/null; then
    printf   "\e[35m✗ [$1] already exists!\e[0m\n"
  else
    printf   "\e[32m  [$1] creating...\e[0m"
    tmuxinator start $1
    printf "\r\e[K\e[33m✓ [$1]\e[0m\n"
  fi
}

# session named '0' is required
if ! is_session_exists 0; then
  printf   "\e[32m  [0] creating ...\e[0m"
  tmux new-session -s 0 -n Console -d
  printf "\r\e[K\e[33m✓ [0]\e[0m\n"
fi

session_names="Monitor YiDa Xcode"
for name in $session_names; do
  start_session $name
done

sleep 1
tmux attach -t 0
