#!/usr/bin/env bash
#x cmdhub: Compile & install Neovim: nvim-smooth

neovim_path="$HOME/.bin/neovim-smooth"

# avoid lua interpreter issue
unset LUA_CPATH LUA_PATH

# compile neovim
cd ~/Git/neovim \
&& git checkout smooth-refresh-rebased \
|| exit 1

rm -rf build &>/dev/null
make clean
make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=${neovim_path}" install
