#!/usr/bin/env bash
#x cmdhub: Compile & install Neovim: nvim-head

neovim_path="$HOME/.bin/neovim-head"

# avoid lua interpreter issue
unset LUA_CPATH LUA_PATH

# backup original neovim version
printf "\e[32mBack up current neovim copy into ${neovim_path}.tmp\e[0m\n"
if [[ -d $neovim_path ]]; then
  rm -rf "${neovim_path}.tmp"
  mv -T "$neovim_path" "${neovim_path}.tmp" || exit
fi

# compile neovim
cd ~/Git/neovim || exit 1

rm -rf build &>/dev/null
make clean
make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=${neovim_path}" install

if (($? != 0)); then
  printf "\e[31mCompiling failed, restore backup ...\e[0m\n"
  mv -T ${neovim_path}.tmp ${neovim_path}
else
  printf "\e[34mNew neovim compiled & installed\e[0m\n"
fi
