#!/usr/bin/env bash
#x cmdhub: Create initial directories for a new iOS project

{
  mkdir Controllers
  mkdir -p Views/ReusableViews
  mkdir Models
  mkdir Storyboards
  mkdir Resources
} &>/dev/null

printf "\e[31mAll directories created:\e[0m\n"
tree -d -L 2
