#!/usr/bin/env bash
#x cmdhub: Delete conflicting files in my cloud repository

cloud_path='/Volumes/Apple_Store/Cloud'
gfind "$cloud_path" -iname '*NSConflict*' -print -delete
gfind "$cloud_path" -iname '*conflicted copy*' -print -delete
gfind "$cloud_path" -iname '*-冲突-*' -print -delete

# vim: ft=sh
