#!/usr/bin/env bash
#x cmdhub: Disable OSX system animations

printf "\e[33mDisable\e[0m\n"

# mission control & expose
printf "\e[34m\t  mission controll & expose animtions\e[0m\n"
defaults write com.apple.dock expose-animation-duration -float 0

# window fade-in/out animations
printf "\e[34m\t  windows fade-in/out animations\e[0m\n"
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool NO

# launch pad
printf "\e[34m\t  launch pad animtions\e[0m\n"
defaults write com.apple.dock springboard-show-duration -float 0
defaults write com.apple.dock springboard-hide-duration -float 0
defaults write com.apple.dock springboard-page-duration -float 0

# dock
printf "\e[34m\t  dock showing & hiding animations\e[0m\n"
defaults write com.apple.dock autohide-time-modifier -float 0
defaults write com.apple.dock autohide-delay -float 0

# finder
printf "\e[34m\t  finder animations\e[0m\n"
defaults write com.apple.finder DisableAllAnimations -bool true

# message & mail
printf "\e[34m\t  mail & message animations\e[0m\n"
defaults write com.apple.Mail DisableSendAnimations -bool true
defaults write com.apple.Mail DisableReplyAnimations -bool true

# quick look window
printf "\e[34m\t  quick look window animations\e[0m\n"
defaults write -g QLPanelAnimationDuration -float 0

# scroll view bouncing
printf "\e[34m\t  scroll view bouncing\e[0m\n"
defaults write -g NSScrollViewRubberbanding -bool false

# resizing windows before and after showing the version browser
# also disabled by NSWindowResizeTime -float 0.001
printf "\e[34m\t  window resizing animations\e[0m\n"
defaults write -g NSDocumentRevisionsWindowTransformAnimation -bool false
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# showing a toolbar or menu bar in full screen
#defaults write -g NSToolbarFullScreenAnimationDuration -float 0

# scrolling column views
printf "\e[34m\t  scrolling column view animations\e[0m\n"
defaults write -g NSBrowserColumnAnimationSpeedMultiplier -float 0

killall Dock
