#!/usr/bin/env bash
#x cmdhub: Restore hosts file for VPN access

content='127.0.0.1  localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
'
sudo echo "$content" > /etc/hosts || exit
sudo killall -HUP mDNSResponder || exit

say 'hosts file restored for VPN access'
