#!/usr/bin/env bash
#x cmdhub: Updates /etc/hosts file from github.com/racaljk

url='https://raw.githubusercontent.com/racaljk/hosts/master/hosts'

printf "\e[33mDownloading from github.com/liuker0x007 ...\e[0m\n"
wget $url -O /tmp/hosts || exit

printf "\e[33mReplacing file ...\e[0m\n"
sudo mv /tmp/hosts /etc/hosts || exit

printf "\e[33mReset DNS cache ...\e[0m\n"
sudo killall -HUP mDNSResponder || exit

say 'Updating hosts done'
printf "\e[35mDONE!\e[0m\n"

#vim: ft=zsh
